version: '2'
services:
  telegraf-forwarder:
    image: kinecosystem/telegraf-forwarder:latest
    ports:
      - '8086:8086'
    links:
     - "grafana_graphite:grafana_graphite"
    restart: on-failure
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "3"
  grafana_graphite:
    build: .
    image: kamon/grafana_graphite
    container_name: kamon-grafana-dashboard
    ports:
      - '80:80'
      - '81:81'
      - '8125:8125/udp'
      - '8126:8126'
      - '2003:2003'
    volumes:
      - ./data/whisper:/opt/graphite/storage/whisper
      - ./data/grafana:/opt/grafana/data
      - ./log/graphite:/opt/graphite/storage/log
      - ./log/supervisor:/var/log/supervisor
